services:
  - type: web
    name: magacin-routing-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn wave_app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
